name: global_configuration
description: A flutter package for managing different configurations and making them available everythere inside the app.
version: 2.0.0
homepage: https://github.com/Ephenodrom/Flutter-Global-Config

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter